# Generated by Django 6.0.4 on 2026-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_coursetest_coursetestattempt_coursetestquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='teacher_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
